export var TEXTURE_INDEX;
(function (TEXTURE_INDEX) {
    TEXTURE_INDEX[TEXTURE_INDEX["BREACH"] = 100] = "BREACH";
    TEXTURE_INDEX[TEXTURE_INDEX["BREACH_DISABLED"] = 101] = "BREACH_DISABLED";
    TEXTURE_INDEX[TEXTURE_INDEX["BG_DUNGEON"] = 1001] = "BG_DUNGEON";
    TEXTURE_INDEX[TEXTURE_INDEX["BG_CREATURA"] = 1002] = "BG_CREATURA";
    TEXTURE_INDEX[TEXTURE_INDEX["BOSS_DUNGEON_BODY"] = 2001] = "BOSS_DUNGEON_BODY";
    TEXTURE_INDEX[TEXTURE_INDEX["BOSS_DUNGEON_FLAME"] = 2002] = "BOSS_DUNGEON_FLAME";
    TEXTURE_INDEX[TEXTURE_INDEX["BASIC_SPELL"] = 12] = "BASIC_SPELL";
})(TEXTURE_INDEX || (TEXTURE_INDEX = {}));
export var BIOME;
(function (BIOME) {
    BIOME[BIOME["SOULS_PLANES"] = 1] = "SOULS_PLANES";
    BIOME[BIOME["RED_SOURCE"] = 2] = "RED_SOURCE";
})(BIOME || (BIOME = {}));
export var QUEST_STAGE;
(function (QUEST_STAGE) {
    QUEST_STAGE[QUEST_STAGE["AVAILABLE"] = 1] = "AVAILABLE";
    QUEST_STAGE[QUEST_STAGE["ACTIVE"] = 2] = "ACTIVE";
    QUEST_STAGE[QUEST_STAGE["COMPLETED"] = 3] = "COMPLETED";
})(QUEST_STAGE || (QUEST_STAGE = {}));
export var QUEST;
(function (QUEST) {
    QUEST[QUEST["BRING_SOULS"] = 0] = "BRING_SOULS";
})(QUEST || (QUEST = {}));
